### ISSUE TITLE
Substantive meaning of notation P(test + |S1, untested) and P(test + |S0, untested)

### ISSUE THREAD

**Issue by rexdouglass** [jadebc/covid19-infections#1]
I'm working through the R code and paper and I have a simple question about notation that's throwing me.

On pg 6 of the Nature pdf, you define a few things that mostly are clear
S_1 Symptomatic
S_0 Asymptomatic
P(S_1|tested) probability of symptomatic "among tested individuals"
P(S_1|untested) probability of symptomatic "among untested individuals"
P(S_0 | test+) probability of symptomatic "among individuals who tested positive"

You then describe
alpha - the ratio of P(test + |S_1, untested)  to the empirical state-level estimate P(test + |tested)
beta - the ratio of  P(test +  |S_0, untested) to the empirical state-level estimate P(test + |tested)

What's unclear to me is that sometimes test+ is being used to mean literally people who have been tested, and other times a theoretical quantity, e.g. would have test+ if they had been tested.

P(test + |S_1, untested) is an example of this. The probability of having a positive test, conditional on being untested is zero. No one who went untested, has a positive test.

So test+ must not mean "among individuals who tested positive" as it's used earlier. Or it must not mean that all of the time.

There must be two different concepts here, (1) were observed to test positive and (2) would have tested positive, and it's not clear to me in the formula or code where each concept is being used.

Does that make sense and am I correct in this interpretation? If so could you help suss out where you intend one of those and where you intend the other?

**Comment by slwu89** [comment]
Hi @rexdouglass, sorry for the delayed response.

You're right, `P(test+ |S_1, untested)` refers to the theoretical, unobserved quantity. Perhaps we could have done a better job with notation to be clear that it is a different quantity. `P(test+ |tested)` should be the only case where this notation is used to denote the empirical, observed quantity. `P(S_0 | test+)` is going to be another case where it means "test+ if they had been tested".

**Comment by rexdouglass** [comment]
Excellent, thank you for the clarification and for a reproducible code base.
